server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 # in query param size:: item0_.item_id in (?, ?, ?...) -> solve n+1

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace